---
- name: WEB SERVER ELIMINATION
  hosts: web
  tasks:
    - name: REMOVE WEB SERVER
      command: yum remove nginx -y

    - name: BLOCK ACCESS TO WEB SERVER
      command: firewall-cmd --remove-service=http --permanent

    - name: RELOAD FIREWALL
      command: firewall-cmd --complete-reload
      

...