---
- name: WEB SERVER SETUP
  hosts: srv
  tasks:
    - name: INSTALL WEB SERVER
      yum: 
        name: httpd
        state: present
    
    - name: ENABLE & START WEB SERVER
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true

    - name: ALLOW ACCESS TO WEB SERVER
      ansible.builtin.firewalld:
        service: http 
        permanent: true
        immediate: true
        state: enabled

    - name: CREATE WEB CONTENT
      ansible.builtin.copy:
        dest: /var/www/html/index.html
        content: |
          <h2>Apache HTTP Web Server</h2>
          <p>Prepared by Ansible</p>

        
...