---
- name: REMOVE WEB SERVER
  hosts: all
  vars_files: vars.yml
  tasks:
    - name: REMOVE PACKAGE
      yum:
        name: "{{ rpm }}"
        state: absent
      notify: 
        - BLOCK HTTP ACCESS

  handlers: 
    - name: BLOCK HTTP ACCESS
      ansible.builtin.firewalld:
        service: "{{ rule }}"
        state: disabled
        immediate: true
        permanent: true

      


...