---
- name: SETUP WEB SERVER CONTENT
  hosts: test
  vars:
    idx: /usr/share/nginx/html/index.html
  tasks:
    - name: DEPLOY WEB CONTENT 
      template:
        src: index.j2
        dest: "{{ idx }}"


...